version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  commit-message:
      prefix: "ci:"
      include: "scope"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    python-packages:
      patterns:
        - "*"
