ci:
    autofix_commit_msg: |
        ci: auto fixes from pre-commit hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    autoupdate_schedule: monthly

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.16.0'
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.5"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Black
