dist: xenial

language: python

jobs:
  include:
    - name: "flake8"
      python: "3.6"
      env: TOX_ENV=flake8
    - name: "coverage"
      python: "3.6"
      env: TOX_ENV=coverage
    - name: "Python 3.6 with django 2.2"
      python:  "3.6"
      env: TOX_ENV=py36-django22
    - name: "Python 3.7 with django 2.2"
      python:  "3.7"
      env: TOX_ENV=py37-django22
    - name: "Python 3.8 with django 2.2"
      python:  "3.8"
      env: TOX_ENV=py38-django22
    - name: "Python 3.6 with django 3.1"
      python:  "3.6"
      env: TOX_ENV=py36-django31
    - name: "Python 3.7 with django 3.1"
      python:  "3.7"
      env: TOX_ENV=py37-django31
    - name: "Python 3.8 with django 3.1"
      python:  "3.8"
      env: TOX_ENV=py38-django31

install:
  - pip install tox coverage codecov sphinx

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - tox -e $TOX_ENV

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - codecov
