name: Lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install ruff
        run: pip install --upgrade ruff
      - name: Run ruff
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: ruff
          run: ruff

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: isort
          run: isort --check --diff django_bleach

  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - run: python -m pip install codespell
      - name: codespell
        uses: codespell-project/actions-codespell@master
