name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, ]
        django-version: [
            '2.2',
            '3.0',  # Strings because otherwise 3.0 becomes 3
            '3.1',
            '3.2'
        ]
        os: [
          ubuntu-20.04,
        ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.django-version }} bleach
        python setup.py install

    - name: Run coverage
      run: coverage run manage.py test --failfast django_bleach

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
