name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        django-version: [
            '2.2',
            '3.2',
            '4.0',
        ]
        os: [
          ubuntu-20.04,
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django==${{ matrix.django-version }} bleach coverage mock
        python setup.py install
    - name: Run coverage
      run: |
        cd testproject
        coverage run --rcfile ../.coveragerc manage.py test --failfast django_bleach

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1

  pre-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [
          ubuntu-20.04,
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --pre django bleach coverage mock
        python setup.py install
    - name: Run tests
      run: |
        cd testproject
        python manage.py test django_bleach
